In [1]:
import numpy as np

In [15]:
arr=np.array(([1,2],[3,4],[5,6]))

In [19]:
zeros=np.zeros((5,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros[0,1]=1

In [24]:
ar=np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace=np.linspace(1,3,5)
lspace

array([1. , 1.5, 2. , 2.5, 3. ])

In [26]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15710427e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 8.45590539e-307,
        6.23054972e-307, 9.34605037e-307, 8.34444713e-308]])

In [27]:
emp_like=np.empty_like(lspace)
emp_like

array([1. , 1.5, 2. , 2.5, 3. ])

In [28]:
ide=np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
ar1=np.arange(20)+1
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
ar1.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [36]:
ar1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
ar1.shape

(20,)

In [50]:
ar2=np.array(([1,32],[3,4]))
ar2sum=ar2.sum(axis=0)
ar2,ar2sum

(array([[ 1, 32],
        [ 3,  4]]),
 array([ 4, 36]))

In [53]:
ar2.T

array([[ 1,  3],
       [32,  4]])

In [57]:
ar2flat=ar2.flat
ar2flat

In [63]:
for item in ar2.flat:
    print(item)

1
32
3
4


In [64]:
ar2.ndim

2

In [67]:
ar2.shape

(2, 2)

In [68]:
ar2.size

4

In [69]:
ar2.nbytes

16

In [73]:
ar2.argmax(),ar2.argmin()

(1, 0)

In [74]:
sort=np.array([1,2,34,342,54,5,6,21,45,23,5])
sort

array([  1,   2,  34, 342,  54,   5,   6,  21,  45,  23,   5])

In [77]:
sorting=sort.argsort()
sorting

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [81]:
sort.argmin(axis=0)

0

In [89]:
a11=np.array(([1,2],[3,4]))
a21=np.array(([5,6],[7,8]))
sum=a11+a21
sum


array([[ 6,  8],
       [10, 12]])

In [90]:
np.sqrt(sum)

array([[2.44948974, 2.82842712],
       [3.16227766, 3.46410162]])

In [91]:
sum

array([[ 6,  8],
       [10, 12]])

In [92]:
np.where(sum>5)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [96]:
sum[1,1]=0
np.count_nonzero(sum),np.nonzero(sum)

(3, (array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64)))

In [99]:
sum

array([[ 6,  8],
       [10,  0]])

In [100]:
import sys

In [101]:
python_array=[1,2,3,4,5]
numpy_array=np.array([1,2,3,4,5])

python_array,numpy_array

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [105]:
python_array_size=sys.getsizeof(1)*len(python_array)
numpy_array_size=numpy_array.itemsize*numpy_array.size
python_array_size,numpy_array_size

(140, 20)

20